### PR TITLE
Spark examples

### PR DESCRIPTION
**Pull request by rvion**
Work in Progress
Should be good to merge as is
More testing required

**Branch can be browsed in github UI here: https://github.com/rvion/spos**

### CODE REVIEW

**Comment by rvion** [comment]
good progress :)
I've simplified the process a lot :pizza:  !

My next step is to unify swarm creation on real machines or virtual machines via docker-machine, so it's no longe necessary to manually configure docker engine.

**Comment by rvion** [comment]
almost there, but I haven't tested it much.
Theorically, it should work :sunny:

**Comment by rvion** [comment]
@randompulse I've made it work :)
It still need some polishing, though, but you can merge it as of now and start testing it

**Comment by rvion** [comment]
The afinity system may not be working 100% yet, but this branch can still be merged.
@randompulse I'm leaving this branch "as-is" for now until I have some feedback :)

**Comment by randompulse** [comment]
feedback : see commits in branch play_with_networking

**Comment by rvion** [comment]
the live diff is here: https://github.com/randompulse/spos/compare/play_with_networking

**Pull request merged**
